services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    restart: always
    ports:
      - 80:80

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    env_file:
      - .env.docker
    volumes:
      - books-data:/var/lib/postgresql/docker_books_db

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "8081:8081"
    env_file:
      - .env.docker
    depends_on:
      - nginx
      - db

volumes:
  books-data:
#  rabbitmq-data:


#  rabbitmq:
#    image: rabbitmq:management
#    hostname: rabbitmq
#    restart: always
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq