services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    restart: always
    ports:
      - 80:80

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: docker_books_db
      POSTGRES_USER: m3mpm
      POSTGRES_PASSWORD: "m3mpm"
    volumes:
      - books-data:/var/lib/postgresql/docker_books_db

  app:
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - "8081:8081"
    depends_on:
      - nginx
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/docker_books_db
      SPRING_DATASOURCE_USERNAME: m3mpm
      SPRING_DATASOURCE_PASSWORD: "m3mpm"
      SPRING_PROFILES_ACTIVE: docker

volumes:
  books-data:
#  rabbitmq-data:


#  rabbitmq:
#    image: rabbitmq:management
#    hostname: rabbitmq
#    restart: always
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    volumes:
#      - rabbitmq-data:/var/lib/rabbitmq