version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres

    volumes:
      - books-data:/var/lib/postgresql/books_data

volumes:
  books-data: