version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: docker_books_db
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_PASSWORD: postgres
    volumes:
      - books-data:/var/lib/postgresql/books_data

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  books-data:
  rabbitmq-data: